universe = docker
docker_image = pytorch/pytorch:2.8.0-cuda12.8-cudnn9-runtime
executable = chr_aa_pred_1.sh

accounting_group = chair_kalinina.long_running

output = runlogs1/train.out
error = runlogs1/train.err
log = runlogs1/train.log
should_transfer_files = YES

request_GPUs = 1
request_CPUs = 32
request_memory = 512G
requirements = (UidDomain == "cs.uni-saarland.de") && (GPUs_GlobalMemoryMb >= 40000)

+WantGPUHomeMounted = true
+WantScratchMounted = true

queue 1
