universe = docker
docker_image = pytorch/pytorch:2.8.0-cuda12.8-cudnn9-runtime
executable = aa_embed_1.sh

output = runlogs1/train.out
error = runlogs1/train.err
log = runlogs1/train.log
should_transfer_files = YES

request_GPUs = 1
request_CPUs = 64
request_memory = 256G
requirements = (UidDomain == "cs.uni-saarland.de") && (GPUs_GlobalMemoryMb >= 40000)

+WantGPUHomeMounted = true
+WantScratchMounted = true

queue 1
