universe = docker
docker_image = gjoschka/kinodata3d-b0:2.3.0-cuda12.1
executable = chr_aa_embed_3.sh

output = runlogs/train.out
error = runlogs/train.err
log = runlogs/train.log
should_transfer_files = YES

request_GPUs = 1
request_CPUs = 8
request_memory = 16G
requirements = (UidDomain == "cs.uni-saarland.de") && (GPUs_GlobalMemoryMb >= 18000)

+WantGPUHomeMounted = true
+WantScratchMounted = true

queue 1
