universe = docker
docker_image = gjoschka/kinodata3d-b0:2.3.0-cuda12.1
executable = chr_aa_embed_1.sh

accounting_group = chair_kalinina.long_running

output = runlogs/train.out
error = runlogs/train.err
log = runlogs/train.log
should_transfer_files = YES

request_GPUs = 1
request_CPUs = 32
request_memory = 64G
requirements = (UidDomain == "cs.uni-saarland.de") && (GPUs_GlobalMemoryMb >= 40000)

+WantGPUHomeMounted = true
+WantScratchMounted = true

queue 1
