universe = docker
docker_image = pytorch/pytorch:2.8.0-cuda12.8-cudnn9-runtime
executable = chr_aa_embed_1.sh

accounting_group = chair_kalinina.long_running

output = runlogs2/train.out
error = runlogs2/train.err
log = runlogs2/train.log
should_transfer_files = YES

request_GPUs = 1
request_CPUs = 32
request_memory = 128G
requirements = (UidDomain == "cs.uni-saarland.de") && (GPUs_GlobalMemoryMb >= 19500)

+WantGPUHomeMounted = true
+WantScratchMounted = true

queue 1
